
const config = { 
    REACT_APP_BASE_URL:"__BASE_URL__",
    REACT_APP_API_BASE_URL:"__API_BASE_URL__",
    REACT_APP_CRM_SSO_CONFIG:"9a222289-b641-41f9-8d13-9c585b645f90",
    REACT_APP_STRIPE_KEY:"__STRIPE_KEY__",
    REACT_APP_STAXX_KEY:"PoundPain-3aca243f3202",
    REACT_APP_SQUARE_APP_KEY:"__SQUARE_APP_KEY__",
    REACT_APP_SQUARE_API_KEY:"__SQUARE_API_KEY__",
    REACT_APP_SQUARE_LOCATION_KEY:"__SQUARE_LOCATION_KEY__",
    REACT_APP_DEPLOY_ENV:"__ENV__",
    REACT_APP_SALESFORCE_URL:"__SALES_FORCE_URL__",
    REACT_APP_GOOGLE_API_KEY:"AIzaSyCjn4U7o_J0AHbNBvkyijucaX_KgTU-46w",
    REACT_APP_BASE_SITE_TYPE:"__SITE_TYPE__"
}

export default config;
